### PR TITLE
Backup-restore & minor fixes

### PR DESCRIPTION
**Pull request by TheMightyV**
As we discussed, I merged my changes into one pull request
- moved backup routines to their own scripts
- added borg backup backend
- added backing up to multiple destinations (for 3-2-1 strategy)
- added backup testing after creating a backup (backup is not a backup until it's tested)
- added snapshot restoration
- split echo messages to debug/info/error
- flipped server_running asserts (I think canon is that assert fails if the condition is false)

### CODE REVIEW

**Comment by kompetenzbolzen** [comment]
Looks good.
But could you maybe also update the Readme?
Also, would you be fine with licensing under MIT? I was planning to relicense anyway, now would be the perfect time.

**Comment by TheMightyV** [comment]
Ah, forgot about the Readme. I'll update soon. 
Sure, I am fine with MIT License.

**Comment by TheMightyV** [comment]
That should do it. Please ignore force pushes :) that did not break anything. Had some problems with git.

**Comment by kompetenzbolzen** [comment]
Merged. Thank You!

**Pull request merged**
